model_name: tiny-llama-a10g
python_version: py310
resources:
  accelerator: A10G
  use_gpu: True
system_packages:
  - python3.10-venv
requirements:
  - sentencepiece
trt_llm:
  build:
    max_input_len: 2000
    max_output_len: 2000
    max_batch_size: 64
    max_beam_width: 1
    base_model: llama
    quantization_type: weights_int8
    checkpoint_repository:
      repo: TinyLlama/TinyLlama-1.1B-Chat-v1.0
      source: HF
